apiVersion: batch/v1
kind: Job
metadata:
  name: nagiosv2
  namespace: nagios
spec:
  completions: 2
  template:
    metadata:
      labels:
        app: nagiosv2
    spec:
      restartPolicy: Never
      containers:
        - image: registry.gitlab.com/quyet.diep/nagios:v2
          name: nagios
